#-- Profile ------------------------------------------------#

include="~~/profiles.conf"
include="~~/subtitles.conf"
include="~~/user.conf"

#-- Video Settings -----------------------------------------#

# Use user.conf to set up settings
profile=base-config

# Set to nvdec/nvdec-copy in case of Nvidia GPU. Setting it to auto may improve performance but may break certain scripts.
hwdec-codecs=all
hr-seek-framedrop=no

tscale=oversample
tscale-blur=0.6991556596428412

# Set to display-resample if you don't have a monitor with VRR.
video-sync=audio

interpolation=no
interpolation-preserve

# Set it to yes in case you can't use the deband shaders.
deband=no
deband-iterations=4
deband-threshold=48
deband-range=16
deband-grain=32

# Set to yes for HDR Passthrough
target-colorspace-hint=no
inverse-tone-mapping=no

dither=no
temporal-dither
dither-depth=auto
error-diffusion=atkinson

scaler-resizes-only=yes

geometry=50%:50%
autofit-larger=75%x75%
autofit-smaller=25%x25%
panscan=0.0

#-- Audio and Language Settings ----------------------------#

profile=sub-sans
sub-use-margins=no
blend-subtitles=no
alang=Japanese,jpn,jp,Korean,kor,ko,English,eng,en
slang=eng,English,en,en-US,US

replaygain=album
volume=100
volume-max=150
audio-pitch-correction=no
audio-channels=auto

demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy

#-- Subtitle and OSD ---------------------------------------#

sub-scale-with-window=yes
sub-ass-scale-with-window=yes
sub-hinting=light
sub-fix-timing=yes
blend-subtitles=no
sub-ass-override=force

osd-font='DM Sans 36pt Medium'
osd-font-size=36
osd-border-size=1.0
osd-color='#eeffffff'
osd-border-color='#dd1c1b22'
osd-shadow-offset=0.0
osd-blur=0.2

no-osc
no-osd-bar
osd-duration=500

border=no

#-- Screenshot ---------------------------------------------#

screenshot-template='%F - [%05n]'
screenshot-sw=yes
screenshot-format=jpg
screenshot-jpeg-quality=99
screenshot-jpeg-source-chroma=no
screenshot-directory=~~desktop/

#-- Misc Settings ------------------------------------------#

cursor-autohide=2500
no-input-default-bindings

idle=once
force-window=yes
keep-open=yes
snap-window
msg-level=all=info,display-tags=warn

loop-file=no
loop-playlist=no

save-position-on-quit=no
watch-later-options-clr

ytdl=yes
ytdl-format=bestvideo+bestaudio/best
ytdl-raw-options=sub-langs=en.*,write-subs=,sub-format=vtt/best
