[base-config]
profile=gpu-vulkan
profile=hig-gpu
hwdec=auto-copy

#-- Auto Profiles --------------------------------------------------------#

[default-fallback]
glsl-shaders-clr
input-commands="script-binding gputoys/gpu-clear"
profile=base-config
profile=sub-sans

[default-audio]
glsl-shaders-clr
input-commands="script-binding gputoys/gpu-clear"
profile=image-gpu

[video-base]
profile=default-fallback
glsl-shader=~~/shaders/Misc/SSimDownscaler.glsl
glsl-shader=~~/shaders/Chroma/JointBilateral.glsl
glsl-shader=~~/shaders/HDeband/hdeband.glsl

[video-upscale]
glsl-shader=~~/shaders/Noise/noise_static_luma.hook
glsl-shader=~~/shaders/FSRCNNX/FSRCNNX_x1_d.glsl
glsl-shader=~~/shaders/RAVU/ravu-lite-ar-r3.hook 
glsl-shader=~~/shaders/RAVU/ravu-zoom-ar-r3.hook

[anime-base]
profile=default-fallback
glsl-shader=~~/shaders/Misc/SSimDownscaler.glsl
glsl-shader=~~/shaders/Chroma/JointBilateral.glsl
glsl-shader=~~/shaders/HDeband/hdeband.glsl
glsl-shader=~~/shaders/Anime4K/Anime4K_Restore_CNN_L.glsl
glsl-shader=~~/shaders/Misc/PixelClipper.glsl

[anime-upscale]
glsl-shader=~~/shaders/Noise/noise_static_luma.hook
glsl-shader=~~/shaders/CuNNy/CuNNy-4x32-DS-Q.glsl
glsl-shader=~~/shaders/RAVU/ravu-zoom-ar-r3.hook
glsl-shader=~~/shaders/AMD/CAS.glsl

[web-base]
profile=default-fallback
glsl-shader=~~/shaders/Misc/SSimDownscaler.glsl
glsl-shader=~~/shaders/Chroma/JointBilateral.glsl
glsl-shader=~~/shaders/HDeband/hdeband.glsl
glsl-shader=~~/shaders/AMD/FSR.glsl
glsl-shader=~~/shaders/AMD/CAS.glsl

[web-upscale]
input-commands="script-binding gputoys/gpu-scale"

[web-hdr]
input-commands="script-binding gputoys/gpu-hdr"
