drc_enabled=yes
drc_knee=2.8
drc_ratio=2
drc_makeup=8
drc_attack=20
drc_release=250
drc_threshold=-20
drc_whitelist=audio

dnm_enabled=no
dnm_gauss=5
dnm_ratio=4
dnm_frame=400
dnm_peak=0.95
dnm_minthres=0
dnm_whitelist=movie

snm_enabled=yes
snm_peak=0.95
snm_expand=2
snm_compress=2
snm_threshold=0.0
snm_raise=0.0001
snm_fall=0.0001
snm_whitelist=video

lnm_enabled=yes
lnm_target=-16
lnm_range=9
lnm_peak=-2
lnm_whitelist=vidmc

sofa_enabled=yes
sofa_file=~~/script-opts/sofa/HRIR_CIRC360.sofa
sofa_type=time
sofa_gain=2
sofa_lfe=4
sofa_rad=2
sofa_whitelist=allmc

vid_threshold=1200
vid_arlimit=1.2
