default=default-fallback
audio=default-audio
image=default-audio

std_base=video-base
std_up=video-upscale
std_down=uhd-downscale
std_long=sub-modern
std_short=sub-sans

anime_base=anime-base
anime_up=anime-upscale
anime_down=uhd-downscale
anime_long=sub-bocchi
anime_short=sub-smooth

web_base=web-base
web_up=web-upscale
web_down=uhd-downscale
web_long=sub-modern
web_short=sub-web
web_hdr=web-hdr